IWYU: INT_MAX and INT_MIN need <climits>
Follow-up to ecc514d490 ("Parser.cpp: Fix undefined behaviour in float
conversion"), which broke the libstdc++ build:

    gen/chrome/browser/devtools/protocol/protocol.cc: In function ‘std::unique_ptr<protocol::Value> protocol::{anonymous}::buildValue(const Char*, const Char*, const Char**, int)’:
    gen/chrome/browser/devtools/protocol/protocol.cc:1304:22: error: ‘INT_MIN’ was not declared in this scope
             if (value >= INT_MIN && value <= INT_MAX && static_cast<int>(value) == value)
                          ^~~~~~~
    gen/chrome/browser/devtools/protocol/protocol.cc:1304:22: note: suggested alternative: ‘WINT_MIN’
             if (value >= INT_MIN && value <= INT_MAX && static_cast<int>(value) == value)
                          ^~~~~~~
                          WINT_MIN
    gen/chrome/browser/devtools/protocol/protocol.cc:1304:42: error: ‘INT_MAX’ was not declared in this scope
             if (value >= INT_MIN && value <= INT_MAX && static_cast<int>(value) == value)
                                              ^~~~~~~
    gen/chrome/browser/devtools/protocol/protocol.cc:1304:42: note: suggested alternative: ‘WINT_MAX’
             if (value >= INT_MIN && value <= INT_MAX && static_cast<int>(value) == value)
                                              ^~~~~~~
                                              WINT_MAX

Bug: chromium:819294, chromium:845816
Change-Id: Iabcece0e83cf0ab26d6bfda5a63239bfd850a33a